### PR TITLE
[DSLX:TS] Error on ref to unbound parametrics.

### LINKED ISSUE #1473: failing to provide a required parametric func slot should produce an actionable error message
**Describe the bug**

Currently when not specifying a parametric `fn` slot, like in the following snippets:
```
import float32;
import std;

pub fn double_fraction_carry(f: float32::F32) -> (uN[float32::F32_FRACTION_SZ], u1) {
    let f = f.fraction as uN[float32::F32_FRACTION_SZ + u32:1];
    let (overflow, f_x2) = std::uadd_with_overflow(f, f);
    (f_x2, overflow)
}
```

The interpreter fails with the following internal error instead of producing an actionable error message:
```
E0612 09:21:19.778839    4433 command_line_utils.cc:45] Could not extract a textual position from error message: INTERNAL: BytecodeEmitter could not find slot or binding for name: V @ xls/dslx/stdlib/std.x:733:6-733:7 stack: 0x5bc9c681b1e4: xls::dslx::BytecodeEmitter::HandleNameRefInternal()
0x5bc9c681a3f1: xls::dslx::BytecodeEmitter::HandleNameRef()
0x5bc9c6b6e6ab: xls::dslx::NameRef::AcceptExpr()
0x5bc9c6818a25: xls::dslx::BytecodeEmitter::HandleInvocation()
0x5bc9c6b70438: xls::dslx::Invocation::AcceptExpr()
0x5bc9c68039e0: xls::dslx::BytecodeEmitter::EmitExpression()
0x5bc9c67ac5db: xls::dslx::internal::(anonymous namespace)::EagerlyPopulateParametricEnvMap()
0x5bc9c67ab49d: xls::dslx::internal::FunctionInstantiator::Instantiate()
0x5bc9c67a8ab3: xls::dslx::InstantiateFunction()
0x5bc9c67487f5: xls::dslx::InstantiateParametricFunction()
0x5bc9c673ed44: xls::dslx::TypecheckInvocation()
0x5bc9c6735748: std::__1::__function::__func<>::operator()()
0x5bc9c679737e: xls::dslx::DeduceInstantiation()
0x5bc9c67981f6: xls::dslx::DeduceInvocation()
0x5bc9c677524b: xls::dslx::(anonymous namespace)::DeduceVisitor::HandleInvocation()
0x5bc9c6b7040b: xls::dslx::Invocation::Accept()
0x5bc9c676950f: xls::dslx::Deduce()
0x5bc9c6735485: std::__1::__function::__func<>::operator()()
0x5bc9c68312a8: xls::dslx::DeduceCtx::Deduce()
0x5bc9c6769a82: xls::dslx::DeduceAndResolve()
0x5bc9c6775365: xls::dslx::(anonymous namespace)::DeduceVisitor::HandleLet()
0x5bc9c6b715bb: xls::dslx::Let::Accept()
0x5bc9c676950f: xls::dslx::Deduce()
0x5bc9c6735485: std::__1::__function::__func<>::operator()()
0x5bc9c68312a8: xls::dslx::DeduceCtx::Deduce()
0x5bc9c676c424: xls::dslx::(anonymous namespace)::DeduceVisitor::HandleStatement()
0x5bc9c6b7143b: xls::dslx::Statement::Accept()
0x5bc9c676950f: xls::dslx::Deduce()
0x5bc9c6735485: std::__1::__function::__func<>::operator()()
0x5bc9c68312a8: xls::dslx::DeduceCtx::Deduce()
0x5bc9c676fa98: xls::dslx::(anonymous namespace)::DeduceVisitor::HandleBlock()
0x5bc9c6b70c4b: xls::dslx::Block::Accept()
0x5bc9c676950f: xls::dslx::Deduce()
0x5bc9c6735485: std::__1::__function::__func<>::operator()()
0x5bc9c68312a8: xls::dslx::DeduceCtx::Deduce()
0x5bc9c6769a82: xls::dslx::DeduceAndResolve()
0x5bc9c6739da4: xls::dslx::TypecheckFunction()
0x5bc9c6732cdb: xls::dslx::TypecheckModule()
0x5bc9c66c12d7: xls::dslx::TypecheckModule()
0x5bc9c66c07c7: xls::dslx::ParseAndTypecheck()
0x5bc9c66b61ea: xls::dslx::ParseAndTest()
0x5bc9c66573b5: main
0x7b7b7ea49d90: [unknown]
: INVALID_ARGUMENT: Provided status is not in recognized error form: INTERNAL: BytecodeEmitter could not find slot or binding for name: V @ xls/dslx/stdlib/std.x:733:6-733:7 stack: 0x5bc9c681b1e4: xls::dslx::BytecodeEmitter::HandleNameRefInternal()
0x5bc9c681a3f1: xls::dslx::BytecodeEmitter::HandleNameRef()
0x5bc9c6b6e6ab: xls::dslx::NameRef::AcceptExpr()
0x5bc9c6818a25: xls::dslx::BytecodeEmitter::HandleInvocation()
0x5bc9c6b70438: xls::dslx::Invocation::AcceptExpr()
0x5bc9c68039e0: xls::dslx::BytecodeEmitter::EmitExpression()
0x5bc9c67ac5db: xls::dslx::internal::(anonymous namespace)::EagerlyPopulateParametricEnvMap()
0x5bc9c67ab49d: xls::dslx::internal::FunctionInstantiator::Instantiate()
0x5bc9c67a8ab3: xls::dslx::InstantiateFunction()
0x5bc9c67487f5: xls::dslx::InstantiateParametricFunction()
0x5bc9c673ed44: xls::dslx::TypecheckInvocation()
0x5bc9c6735748: std::__1::__function::__func<>::operator()()
0x5bc9c679737e: xls::dslx::DeduceInstantiation()
0x5bc9c67981f6: xls::dslx::DeduceInvocation()
0x5bc9c677524b: xls::dslx::(anonymous namespace)::DeduceVisitor::HandleInvocation()
0x5bc9c6b7040b: xls::dslx::Invocation::Accept()
0x5bc9c676950f: xls::dslx::Deduce()
0x5bc9c6735485: std::__1::__function::__func<>::operator()()
0x5bc9c68312a8: xls::dslx::DeduceCtx::Deduce()
0x5bc9c6769a82: xls::dslx::DeduceAndResolve()
0x5bc9c6775365: xls::dslx::(anonymous namespace)::DeduceVisitor::HandleLet()
0x5bc9c6b715bb: xls::dslx::Let::Accept()
0x5bc9c676950f: xls::dslx::Deduce()
0x5bc9c6735485: std::__1::__function::__func<>::operator()()
0x5bc9c68312a8: xls::dslx::DeduceCtx::Deduce()
0x5bc9c676c424: xls::dslx::(anonymous namespace)::DeduceVisitor::HandleStatement()
0x5bc9c6b7143b: xls::dslx::Statement::Accept()
0x5bc9c676950f: xls::dslx::Deduce()
0x5bc9c6735485: std::__1::__function::__func<>::operator()()
0x5bc9c68312a8: xls::dslx::DeduceCtx::Deduce()
0x5bc9c676fa98: xls::dslx::(anonymous namespace)::DeduceVisitor::HandleBlock()
0x5bc9c6b70c4b: xls::dslx::Block::Accept()
0x5bc9c676950f: xls::dslx::Deduce()
0x5bc9c6735485: std::__1::__function::__func<>::operator()()
0x5bc9c68312a8: xls::dslx::DeduceCtx::Deduce()
0x5bc9c6769a82: xls::dslx::DeduceAndResolve()
0x5bc9c6739da4: xls::dslx::TypecheckFunction()
0x5bc9c6732cdb: xls::dslx::TypecheckModule()
0x5bc9c66c12d7: xls::dslx::TypecheckModule()
0x5bc9c66c07c7: xls::dslx::ParseAndTypecheck()
0x5bc9c66b61ea: xls::dslx::ParseAndTest()
0x5bc9c66573b5: main
0x7b7b7ea49d90: [unknown]

Error: INTERNAL: BytecodeEmitter could not find slot or binding for name: V @ xls/dslx/stdlib/std.x:733:6-733:7 stack: 0x5bc9c681b1e4: xls::dslx::BytecodeEmitter::HandleNameRefInternal()
0x5bc9c681a3f1: xls::dslx::BytecodeEmitter::HandleNameRef()
0x5bc9c6b6e6ab: xls::dslx::NameRef::AcceptExpr()
0x5bc9c6818a25: xls::dslx::BytecodeEmitter::HandleInvocation()
0x5bc9c6b70438: xls::dslx::Invocation::AcceptExpr()
0x5bc9c68039e0: xls::dslx::BytecodeEmitter::EmitExpression()
0x5bc9c67ac5db: xls::dslx::internal::(anonymous namespace)::EagerlyPopulateParametricEnvMap()
0x5bc9c67ab49d: xls::dslx::internal::FunctionInstantiator::Instantiate()
0x5bc9c67a8ab3: xls::dslx::InstantiateFunction()
0x5bc9c67487f5: xls::dslx::InstantiateParametricFunction()
0x5bc9c673ed44: xls::dslx::TypecheckInvocation()
0x5bc9c6735748: std::__1::__function::__func<>::operator()()
0x5bc9c679737e: xls::dslx::DeduceInstantiation()
0x5bc9c67981f6: xls::dslx::DeduceInvocation()
0x5bc9c677524b: xls::dslx::(anonymous namespace)::DeduceVisitor::HandleInvocation()
0x5bc9c6b7040b: xls::dslx::Invocation::Accept()
0x5bc9c676950f: xls::dslx::Deduce()
0x5bc9c6735485: std::__1::__function::__func<>::operator()()
0x5bc9c68312a8: xls::dslx::DeduceCtx::Deduce()
0x5bc9c6769a82: xls::dslx::DeduceAndResolve()
0x5bc9c6775365: xls::dslx::(anonymous namespace)::DeduceVisitor::HandleLet()
0x5bc9c6b715bb: xls::dslx::Let::Accept()
0x5bc9c676950f: xls::dslx::Deduce()
0x5bc9c6735485: std::__1::__function::__func<>::operator()()
0x5bc9c68312a8: xls::dslx::DeduceCtx::Deduce()
0x5bc9c676c424: xls::dslx::(anonymous namespace)::DeduceVisitor::HandleStatement()
0x5bc9c6b7143b: xls::dslx::Statement::Accept()
0x5bc9c676950f: xls::dslx::Deduce()
0x5bc9c6735485: std::__1::__function::__func<>::operator()()
0x5bc9c68312a8: xls::dslx::DeduceCtx::Deduce()
0x5bc9c676fa98: xls::dslx::(anonymous namespace)::DeduceVisitor::HandleBlock()
0x5bc9c6b70c4b: xls::dslx::Block::Accept()
0x5bc9c676950f: xls::dslx::Deduce()
0x5bc9c6735485: std::__1::__function::__func<>::operator()()
0x5bc9c68312a8: xls::dslx::DeduceCtx::Deduce()
0x5bc9c6769a82: xls::dslx::DeduceAndResolve()
0x5bc9c6739da4: xls::dslx::TypecheckFunction()
0x5bc9c6732cdb: xls::dslx::TypecheckModule()
0x5bc9c66c12d7: xls::dslx::TypecheckModule()
0x5bc9c66c07c7: xls::dslx::ParseAndTypecheck()
0x5bc9c66b61ea: xls::dslx::ParseAndTest()
0x5bc9c66573b5: main
0x7b7b7ea49d90: [unknown]
```

### PR DESCRIPTION
**Pull request by cdleary**
Previously we'd get an internal error by running head-first into the bytecode interpreter and it returning us an unbound error from its execution.

This institutes a look-before-you-leap: we look for freevars from the parametric expression that are present in the parametric bindings, and check that those are present in the parametric environment map. If they are not, we provide a more precise and helpful error message.

Ideally we'd be even more aggressive about reporting parametrics that are unbound at the point of instantiation, that is what #1495 is for and why there's a bit of code stubbed out with a TODO in this PR -- there is some investigation needed for the examples that fail with that enabled, but this change strictly moves the ball forward by resolving the issue seen in #1473.

Fixes #1473
One step towards #1495

### CODE REVIEW

File: xls/dslx/frontend/ast.cc [hunk 1]
```diff
@@ -401,28 +408,33 @@ absl::flat_hash_set<std::string> FreeVariables::Keys() const {
...
   }
   return freevars;
 }
 
+FreeVariables GetFreeVariablesByPos(const AstNode* node, const Pos* start_pos) {
+  std::function<bool(const NameRef&)> consider_free = nullptr;
+  if (start_pos != nullptr) {
+    consider_free = [start_pos](const NameRef& name_ref) {
+      std::optional<Pos> name_def_start = name_ref.GetNameDefStart();
+      return !name_def_start.has_value() || name_def_start.value() < *start_pos;
```
Comment (ericastor) [inline xls/dslx/frontend/ast.cc:432]: I'm probably just missing something - but I don't understand this code. It seems like we're saying that we should consider the variable free if:

1. it's not defined anywhere (seems correct), or
2. the definition comes *before* the current position... which seems backwards, since that sounds like the situation in which the variable would be bound?

I acknowledge that this seems to work, and isn't a change from what was here before, but it seems worth a comment to clarify how.

Comment (cdleary) [reply xls/dslx/frontend/ast.cc:432]: Did you see the comment in the header file?

```
// Retrieves all the free variables (references to names that are defined                                                               
// prior to start_pos) that are transitively in this AST subtree.                                                                       
//
// For example, if given the AST node for this function:                                                                                
//
//    const FOO = u32:42;
//    fn main(x: u32) { FOO+x }                                                                                                         
//
// And *using the starting point of the function* as the `start_pos`, the `FOO`                                                         
// will be flagged as a free variable and returned.
```

The `start_pos` given is a way to approximate "free variable with respect to this AST construct". i.e. all the references with defs that are defined before this `start_pos` point are considered free. This gives an easy way to say "everything defined inside the body we don't need to worry about, only tell me about references to things before this lexical position in the file.

LMK if you have a way you'd rephrase that header comment for more clarity.

Comment (cdleary) [reply xls/dslx/frontend/ast.cc:432]: (For now just added this paragraph to the API comment as an additional note, on the assumption maybe it's rephrasing in a clearer way.)

**Review by ericastor — APPROVED** [review]

**Comment by allight** [comment]
approved internally

**Review by allight — APPROVED** [review]
